const THREE_VERSION_MAJOR = '174'
const THREE_VERSION_MINOR = '0'

export const THREE_TAG = `r${THREE_VERSION_MAJOR}`
export const THREE_VERSION = `0.${THREE_VERSION_MAJOR}.${THREE_VERSION_MINOR}`

export const LIL_GUI_VERSION = '0.20.0'
